### ISSUE TITLE
Add indexing "task" from folio-dev to searchworks-folio-dev on -stage

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#652]
(Potentially blocked by #643? At least consider if eye->systemd would have an impact or suggest an alternate approach) 

This might look like the rake tasks that load data in from purl-fetcher. Do we use still use kafka?

**Comment by cbeer** [comment]
Yes, we want to hook up the folio source-record-stream (and maybe other changed streams?) to kafka. 

We've done this in #646 already, because we had no better way of harvesting FOLIO incrementally. It was easy enough to follow the existing patterns, and gives us an easy way to parallelize the indexing tasks.

For indexing, we can use a configuration like:
```yaml
 - name: folio_dev_indexer
    num_processes: 8
    traject_settings:
      - kafka.topic=marc_folio
      - kafka.consumer_group_id=traject
      - solr.url=http://sul-solr.stanford.edu/solr/searchworks-folio-dev
      - okapi.url=https://user:password@okapi-dev.stanford.edu
      - reader_class_name=Traject::KafkaFolioReader
    rvm_ruby: ruby-3.1.2
    config_file: ./lib/traject/config/folio_config.rb
```
