### ISSUE TITLE
Indexing in staging should generate geo records with links to staging infrastructure

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#742]
currently the indexer hardcodes the location of our geoservers:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/16ebd867985d23ea53efd1e3843e4efa83be1b23/lib/traject/config/geo_config.rb#L132-L137

this is then used to populate the "references" field used by Earthworks to render map previews and populate the web service links:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/16ebd867985d23ea53efd1e3843e4efa83be1b23/lib/traject/config/geo_config.rb#L267-L310

the result is that records in the `kurma-earthworks-v1-stage` solr core still point to production infrastructure (production geoserver, production PURL, production stacks, etc).

it would be helpful for earthworks-stage to have records that actually point to staging infrastructure (in particular, the staging geoserver) so that we can test content by releasing it from argo-stage and seeing how it appears/renders in earthworks-stage, without impacting production at all.

we might be able to do this by allowing `Constants::GEOWEBSERVICES` to look up environment-based config values, so we can change them in staging.

**Comment by thatbudakguy** [comment]
current configuration on the indexing boxes has:
```yaml
  - name: earthworks-stage-indexer
    traject_settings:
      - kafka.topic=purl_fetcher_prod
      - kafka.consumer_group_id=earthworks-stage-indexer
      - solr.url=http://sul-solr.stanford.edu/solr/kurma-earthworks-v1-stage
    rvm_ruby: ruby-3.1.2
    config_file: ./lib/traject/config/geo_config.rb
```

we probably want to instead point at the `purl_fetcher_stage` kafka topic.
